---
name: HUGO build
author: Arne Tarara
description: Building a static site in HUGO and measuring the energy and carbon cost

services:
  hugo-container:
    image: klakegg/hugo:0.101.0-alpine
    command: shell
    setup-commands:
      - cp -R /tmp/repo /src

flow:
  - name: Build Hugo
    container: hugo-container
    commands:
      - type: console
        command: hugo -s /src/repo
        note: Starting HUGO build